// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUmbracoElementFinderApiV1UsageByAliasData, GetUmbracoElementFinderApiV1UsageByAliasErrors, GetUmbracoElementFinderApiV1UsageByAliasResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getUmbracoElementFinderApiV1UsageByAlias = <ThrowOnError extends boolean = false>(options: Options<GetUmbracoElementFinderApiV1UsageByAliasData, ThrowOnError>) => (options.client ?? client).get<GetUmbracoElementFinderApiV1UsageByAliasResponses, GetUmbracoElementFinderApiV1UsageByAliasErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/element-finder/api/v1/usage/{alias}',
    ...options
});
