// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Details = {
    pageName: string;
    url: string;
    id: string;
};

export type Usage = {
    usages: Array<Details>;
};

export type GetUmbracoElementFinderApiV1UsageByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/element-finder/api/v1/usage/{alias}';
};

export type GetUmbracoElementFinderApiV1UsageByAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoElementFinderApiV1UsageByAliasResponses = {
    /**
     * OK
     */
    200: Usage;
};

export type GetUmbracoElementFinderApiV1UsageByAliasResponse = GetUmbracoElementFinderApiV1UsageByAliasResponses[keyof GetUmbracoElementFinderApiV1UsageByAliasResponses];
